
const DAY_IN_MILLISECONDS = 1000*60*60*24;
const HOUR_IN_MILLISECONDS = 1000*60*60;
const MINUTES_IN_MILLISECONDS = 1000*60;
const ANIMAL_ACTIVITY_NOTIFICATION_HOURS = 24;
const ANIMAL_FEEDING_NOTIFICATION_HOURS = 6;
const ADVANCE_DAYS_FOR_ZOO_EVENT_GENERATION = 90;

export {
    DAY_IN_MILLISECONDS, 
    HOUR_IN_MILLISECONDS,
    MINUTES_IN_MILLISECONDS,
    ANIMAL_ACTIVITY_NOTIFICATION_HOURS,
    ANIMAL_FEEDING_NOTIFICATION_HOURS,
    ADVANCE_DAYS_FOR_ZOO_EVENT_GENERATION
};