
const DAY_IN_MILLISECONDS = 1000*60*60*24;
const HOUR_IN_MILLISECONDS = 1000*60*60;
const ANIMAL_ACTIVITY_NOTIFICATION_HOURS = 3;

export {
    DAY_IN_MILLISECONDS, 
    HOUR_IN_MILLISECONDS,
    ANIMAL_ACTIVITY_NOTIFICATION_HOURS
};