enum KeeperType {
  SENIOR_KEEPER = "SENIOR_KEEPER",
  KEEPER = "KEEPER"
}

enum PlannerType {
  NUTRITIONIST = "NUTRITIONIST",
  CURATOR = "CURATOR"
}

enum GeneralStaffType {
  MAINTENANCE = "MAINTENANCE",
  OPERATE = "OPERATE"
}

enum SensorType{
  TEMPERATURE = "TEMPERATURE",
  LIGHT = "LIGHT", 
  HUMIDITY = "HUMIDITY",
  SOUND = "SOUND",
  MOTION = "MOTION",
  HUMAN = "HUMAN"
}

enum FacilityType{
  INFORMATION_CENTRE = "INFORMATION_CENTRE",
  ZOO_DIRECTORY = "ZOO_DIRECTORY", 
  AMPHITHEATRE = "AMPHITHEATRE", 
  GAZEBO = "GAZEBO",
  AED = "AED",
  RESTROOM = "RESTROOM",
  NURSERY = "NURSERY",
  FIRST_AID = "FIRST_AID",
  BENCHES = "BENCHES",
  PLAYGROUND = "PLAYGROUND",
  TRAMSTOP = "TRAMSTOP",
  PARKING = "PARKING"
}

enum Specialization{
  MAMMAL="MAMMAL",
  BIRD = "BIRD",
  FISH= "FISH",
  REPTILE = "REPTILE",
  AMPHIBIAN= "AMPHIBIAN"
}

enum MedicalSupplyType{
  FIRST_AID="FIRST_AID",
  MEDICATION="MEDICATION",
  DIAGNOSTIC_TOOL="DIAGNOSTIC_TOOL",
  SURGICAL_TOOL="SURGICAL_TOOL",
  FLUID_ADMINISTRATION="FLUID_ADMINISTRATION",
  DENTAL="DENTAL",
  EMERGENCY="EMERGENCY",
  FEEDING_TUBE_AND_SYRINGES="FEEDING_TUBE_AND_SYRINGES",
  LABORATORY="LABORATORY",
  PPE="PPE"
}

export {KeeperType, PlannerType, GeneralStaffType, SensorType, FacilityType, Specialization, MedicalSupplyType};