enum KeeperType {
  SENIOR_KEEPER = "SENIOR_KEEPER",
  KEEPER = "KEEPER"
}

enum PlannerType {
  NUTRITIONIST = "NUTRITIONIST",
  CURATOR = "CURATOR",
  OPERATIONS_MANAGER = "OPERATIONS_MANAGER"
}

enum GeneralStaffType {
  MAINTENANCE = "MAINTENANCE",
  OPERATE = "OPERATE"
}

enum SensorType{
  TEMPERATURE = "TEMPERATURE",
  LIGHT = "LIGHT", 
  HUMIDITY = "HUMIDITY",
  SOUND = "SOUND",
  MOTION = "MOTION",
  HUMAN = "HUMAN"
}

enum FacilityType{
  INFORMATION_CENTRE = "INFORMATION_CENTRE",
  ZOO_DIRECTORY = "ZOO_DIRECTORY", 
  AMPHITHEATRE = "AMPHITHEATRE", 
  GAZEBO = "GAZEBO",
  AED = "AED",
  RESTROOM = "RESTROOM",
  NURSERY = "NURSERY",
  FIRST_AID = "FIRST_AID",
  BENCHES = "BENCHES",
  PLAYGROUND = "PLAYGROUND",
  TRAMSTOP = "TRAMSTOP",
  PARKING = "PARKING"
}

enum Specialization{
  MAMMAL="MAMMAL",
  BIRD = "BIRD",
  FISH= "FISH",
  REPTILE = "REPTILE",
  AMPHIBIAN= "AMPHIBIAN"
}

enum MedicalSupplyType{
  FIRST_AID="FIRST_AID",
  MEDICATION="MEDICATION",
  DIAGNOSTIC_TOOL="DIAGNOSTIC_TOOL",
  SURGICAL_TOOL="SURGICAL_TOOL",
  FLUID_ADMINISTRATION="FLUID_ADMINISTRATION",
  DENTAL="DENTAL",
  EMERGENCY="EMERGENCY",
  FEEDING_TUBE_AND_SYRINGES="FEEDING_TUBE_AND_SYRINGES",
  LABORATORY="LABORATORY",
  PPE="PPE"
}

enum ConservationStatus{
  DATA_DEFICIENT = "DATA_DEFICIENT",
  DOMESTICATED = "DOMESTICATED",
  LEAST_CONCERN = "LEAST_CONCERN",
  NEAR_THREATENED = "NEAR_THREATENED",
  VULNERABLE= "VULNERABLE",
  ENDANGERED= "ENDANGERED",
  CRITICALLY_ENDANGERED = "CRITICALLY_ENDANGERED",
  EXTINCT_IN_WILD= "EXTINCT_IN_WILD"
}

enum Continent{
  AFRICA = "AFRICA",
  ASIA="ASIA",
  EUROPE= "EUROPE",
  NORTH_AMERICA ="NORTH_AMERICA",
  SOUTH_OR_CENTRAL_AMERICA= "SOUTH_OR_CENTRAL_AMERICA",
  OCEANIA="OCEANIA"
}

enum GroupSexualDynamic{
  MONOGAMOUS="MONOGAMOUS",
  PROMISCUOUS="PROMISCUOUS",
  POLYGYNOUS="POLYGYNOUS",
  POLYANDROUS="POLYANDROUS"
}

enum PresentationContainer {}
enum PresentationMethod{}
enum PresentationLocation{}
enum AnimalGrowthState{}

enum AnimalSex{
  MALE="MALE",
  FEMALE="FEMALE",
  UNKNOWN="UNKNOWN",
  ASEXUAL="ASEXUAL"
}

enum AcquisitionMethod{
  INFANT="INFANT",
  JUVENILE="JUVENILE",
  ADOLESCENT="ADOLESCENT",
  ADULT="ADULT",
  ELDER="ELDER"
}

enum AnimalGrowthStage{
  CAPTIVE_BRED="CAPTIVE_BRED",
  WILD_CAPTURED="WILD_CAPTURED",
  TRANSFERRED_IN="TRANSFERRED_IN"
}

enum AnimalStatusType{}

enum Biome{
  AQUATIC="AQUATIC",
  DESERT="DESERT",
  GRASSLAND="GRASSLAND",
  TAIGA="TAIGA",
  TEMPERATE="TEMPERATE",
  TROPICAL="TROPICAL",
  TUNDRA="TUNDRA"
}

export {KeeperType, PlannerType, GeneralStaffType, SensorType, FacilityType, Specialization, MedicalSupplyType, ConservationStatus, Continent, GroupSexualDynamic, PresentationContainer, PresentationMethod, PresentationLocation, AnimalGrowthState, AnimalSex, AcquisitionMethod, AnimalGrowthStage, AnimalStatusType, Biome};